// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeh4v2Neu4L15ZZvCeetC_HBMj0CrAtwg',
    appId: '1:925516890094:web:a1e0b40207a3e1eff898ff',
    messagingSenderId: '925516890094',
    projectId: 'timeeee',
    authDomain: 'timeeee.firebaseapp.com',
    storageBucket: 'timeeee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJJ4YQSQiVXi_YW2IndSHsfoNE8UPeF6A',
    appId: '1:925516890094:android:aab65bd60c130a7bf898ff',
    messagingSenderId: '925516890094',
    projectId: 'timeeee',
    storageBucket: 'timeeee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPqdnGSk6TChCEkgfEGPqzAd5FN2cnG94',
    appId: '1:925516890094:ios:2c523196936bd17ff898ff',
    messagingSenderId: '925516890094',
    projectId: 'timeeee',
    storageBucket: 'timeeee.appspot.com',
    iosClientId: '925516890094-lk9c9ic726ehuov0cmuov221uvuvhqhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.timey',
  );
}
